[workspace]
members = [
    "rust/substreams",
    "rust/substreams-macro",
    "rust/test"
]
exclude = [
    "pipeline/test_data/simple_substreams"
]

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"